apiVersion: v1
kind: Service
metadata:
  name: mydb
  labels:
    app: mydb
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    role: active
    app: mydb
---
apiVersion: v1
kind: Service
metadata:
  name: mydb-read
  labels:
    app: mydb
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app: mydb
