apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mydb-role
subjects:
- kind: User
  name: system:serviceaccount:default:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: mydb-role
  apiGroup: rbac.authorization.k8s.io
