apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa-front
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-front
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa-back
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-back
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
